name: Build and push docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
  
      - name: Checkout code
        uses: actions/checkout@v4

      - name: standardjs-ga
        uses: devjoca/standardjs-action@0.4.0
    

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: darynaspyskan/repo1:frontend-${{ github.sha }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: darynaspyskan/repo1:backend-${{ github.sha }}
